# Use an official Python image
FROM python:3.9

# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# Set the working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app files
COPY . .

# Expose the port Flask runs on
EXPOSE 5000


CMD ["sh", "-c", "python db_seeding.py && gunicorn -b 0.0.0.0:5000 app:app"]
