version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://new_user:user_password@db/test_db
      OPENAI_API_KEY: OPENAI-API-KEY
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data:
